
import { GeneratedClass } from '../types';

export class KotlinGenerator {
  private classes: GeneratedClass[] = [];
  private seenClasses: Set<string> = new Set();

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('') || 'AutoGenerated';
  }

  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  private inferType(key: string, value: any): string {
    if (value === null) return "Any?";
    if (typeof value === "string") return "String";
    if (typeof value === "number") {
      return Number.isInteger(value) ? "Int" : "Double";
    }
    if (typeof value === "boolean") return "Boolean";
    
    if (Array.isArray(value)) {
      if (value.length === 0) return "List<Any>";
      const itemType = this.inferType(key + "Item", value[0]);
      return `List<${itemType}>`;
    }
    
    if (typeof value === "object") {
      const className = this.toPascalCase(key);
      this.generateClass(className, value);
      return className;
    }

    return "Any";
  }

  private generateClass(className: string, obj: any) {
    if (this.seenClasses.has(className)) return;
    this.seenClasses.add(className);

    let code = `import com.google.gson.annotations.SerializedName\n\n`;
    code += `data class ${className}(\n`;
    
    const keys = Object.keys(obj);
    keys.forEach((key, index) => {
      const type = this.inferType(key, obj[key]);
      const propertyName = this.toCamelCase(key);
      const isLast = index === keys.length - 1;
      
      code += `    @SerializedName("${key}")\n`;
      code += `    val ${propertyName}: ${type}${isLast ? "" : ","}\n`;
    });

    code += `)`;
    
    this.classes.push({ className, code });
  }

  public generate(json: any, rootName: string = "Response"): GeneratedClass[] {
    this.classes = [];
    this.seenClasses = new Set();
    
    if (Array.isArray(json)) {
       if (json.length > 0) {
          this.generateClass(rootName, json[0]);
       }
    } else if (typeof json === 'object' && json !== null) {
      this.generateClass(rootName, json);
    }
    
    return this.classes.reverse();
  }
}
